#!/usr/bin/python

import sys
sys.path.insert(0, '.')

import maglica.cli.dispatcher
import logging
logging.getLogger().setLevel(logging.DEBUG)
logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s')

if __name__ == '__main__':
    maglica.cli.dispatcher.main()
